version: '3.9'

services:
  api:
    container_name: "SERVICE_API"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SwaggerSettings__ServiceName=StockBot
    ports:
      - "8000:80"
