version: '3.9'

services:
  # chatapi:
  #   container_name: "CHAT_API"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #     - SwaggerSettings__ServiceName=StockBot
  #   ports:
  #     - "8000:80"
  stockconsumersub:
    container_name: "STOCK_CONSUMER_SUB_API"
    build:
      context: .\StockConsumer\
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQSettings__HostName=rabbitmq-container
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__User=test_user
      - RabbitMQSettings__Password=test_password
      - RabbitMQSettings__QueueName=stock_queue
      - ChatHubUrl=http://chatsignalrhub/chatHub
    depends_on:
      - rabbitmq-container
      - chatsignalrhub
    restart: on-failure
    networks:
      - backend_chat
  chatsignalrhub:
    container_name: "CHAT_SIGNALR_HUB_API"
    build:
      context: .\SignalRHub\
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8001:80"
    networks:
      - backend_chat
  chatbotapi:
    container_name: "CHAT_BOT_API"
    build:
      context: .\StockBot\
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RedisCache__Host=redis
      - RedisCache__Port=6379
      - RabbitMQSettings__HostName=rabbitmq-container
      - RabbitMQSettings__Port=5672
      - RabbitMQSettings__ExchangeName=amq.topic
      - RabbitMQSettings__ExchangeType=topic
      - RabbitMQSettings__RoutingKey=stock_key
      - RabbitMQSettings__QueueName=stock_queue
      - RabbitMQSettings__User=test_user
      - RabbitMQSettings__Password=test_password
    ports:
      - "8002:80"
    depends_on:
      - rabbitmq-container
      - redis
    networks:
      - backend_chat
  redis:
    container_name: "REDIS_SERVER"
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend_chat
  rabbitmq-container:
    container_name: "RABBIT_MQ"
    hostname: rabbitmq-container
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=test_user
      - RABBITMQ_DEFAULT_PASS=test_password
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - backend_chat
networks:
  backend_chat:
    driver: bridge
